import * as icons from './assets/icons';

export const ny_bullets = new Map();
ny_bullets.set('1', icons.ny_1);
ny_bullets.set('2', icons.ny_2);
ny_bullets.set('3', icons.ny_3);
ny_bullets.set('4', icons.ny_4);
ny_bullets.set('5', icons.ny_5);
ny_bullets.set('6', icons.ny_6);
ny_bullets.set('7', icons.ny_7);
ny_bullets.set('A', icons.ny_A);
ny_bullets.set('C', icons.ny_C);
ny_bullets.set('E', icons.ny_E);
ny_bullets.set('B', icons.ny_B);
ny_bullets.set('D', icons.ny_D);
ny_bullets.set('F', icons.ny_F);
ny_bullets.set('M', icons.ny_M);
ny_bullets.set('G', icons.ny_G);
ny_bullets.set('J', icons.ny_J);
ny_bullets.set('Z', icons.ny_Z);
ny_bullets.set('L', icons.ny_L);
ny_bullets.set('S', icons.ny_S);
ny_bullets.set('N', icons.ny_N);
ny_bullets.set('Q', icons.ny_Q);
ny_bullets.set('R', icons.ny_R);
ny_bullets.set('W', icons.ny_W);
ny_bullets.set('T', icons.ny_T);
ny_bullets.set('IBX', icons.IBX);
ny_bullets.set('LIRR', icons.LIRR);
ny_bullets.set('MNR', icons.MNR);